FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

# Виправлений шлях із подвійною вкладеністю зі скріншота
WORKDIR /src/SchoolJournal.Blazor/SchoolJournal.Blazor
RUN dotnet publish "SchoolJournal.Blazor.csproj" -c Release -o /app/publish /p:UseAppHost=false -p:NoWarn=1591

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_hostBuilder__reloadConfigOnChange=false
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "SchoolJournal.Blazor.dll"]